#!/usr/bin/env python3
"""Sync Mintlify MDX docs into the hai-platform skill as bundled references.

Copies every .mdx under SRC into DEST (mirroring the tree, deleting stale
files) and generates DEST/index.md mapping each page to its live URL on the
hub. Output is deterministic so re-running on unchanged sources is a no-op —
the CI workflow relies on that to decide whether to open a PR.

Usage:
    python3 sync_hub_docs.py <src-dir> <dest-dir> [--route agent-api] [--base-url https://hub.hcompany.ai]

Stdlib only — runnable locally and in a bare CI runner.
"""

import argparse
import os
import shutil
import sys


def frontmatter(path: str) -> dict[str, str]:
    """Best-effort parse of simple `key: value` Mintlify frontmatter."""
    meta: dict[str, str] = {}
    with open(path, encoding="utf-8") as f:
        if f.readline().strip() != "---":
            return meta
        for line in f:
            line = line.rstrip("\n")
            if line.strip() == "---":
                break
            if ":" in line and not line.startswith((" ", "\t")):
                key, _, value = line.partition(":")
                meta[key.strip()] = value.strip().strip("'\"")
    return meta


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("src", help="docs source dir (e.g. <docs-checkout>/agent-api)")
    p.add_argument("dest", help="destination dir inside the skill")
    p.add_argument("--route", default="agent-api", help="URL route of src on the hub")
    p.add_argument("--base-url", default="https://hub.hcompany.ai")
    args = p.parse_args()

    if not os.path.isdir(args.src):
        sys.exit(f"error: source dir not found: {args.src}")

    pages: list[tuple[str, dict[str, str]]] = []  # (relpath without .mdx, frontmatter)
    for root, dirs, files in os.walk(args.src):
        dirs.sort()
        for name in sorted(files):
            if name.endswith(".mdx"):
                full = os.path.join(root, name)
                rel = os.path.relpath(full, args.src)
                pages.append((rel[: -len(".mdx")], frontmatter(full)))
    if not pages:
        sys.exit(f"error: no .mdx files under {args.src} — wrong directory?")

    # mirror: wipe and re-copy so deletions in the docs repo propagate
    if os.path.isdir(args.dest):
        shutil.rmtree(args.dest)
    for rel, _ in pages:
        src_file = os.path.join(args.src, rel + ".mdx")
        dest_file = os.path.join(args.dest, rel + ".mdx")
        os.makedirs(os.path.dirname(dest_file), exist_ok=True)
        shutil.copyfile(src_file, dest_file)

    lines = [
        f"# {args.route} — official hub docs (synced)",
        "",
        f"Mirrored from the Mintlify source; live version: {args.base_url}/{args.route}.",
        "Do not edit by hand — regenerated by .github/workflows/sync-hub-docs.yml.",
    ]
    section = None
    for rel, meta in sorted(pages, key=lambda x: (os.path.dirname(x[0]), x[0])):
        directory = os.path.dirname(rel) or "."
        if directory != section:
            section = directory
            lines += ["", f"## {args.route}" + ("" if directory == "." else f"/{directory}"), ""]
        title = meta.get("title") or os.path.basename(rel)
        desc = meta.get("description", "")
        live = f"{args.base_url}/{args.route}/{rel}"
        lines.append(f"- [{title}]({rel}.mdx){' — ' + desc if desc else ''} · [live]({live})")
    with open(os.path.join(args.dest, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"synced {len(pages)} pages -> {args.dest}")


if __name__ == "__main__":
    main()
